services:
  # run with
  # $ docker compose run pca-cm
  pca-cm:
    build: .
    container_name: app
    stdin_open: true
    tty: true
    command: bash -c "mkdir -p /data/root-ca && cd /data/root-ca && exec bash"
    volumes:
      - ./data:/data
      - ./public:/public
      - ./private-encrypted:/private-encrypted